### ISSUE TITLE
Question: What to do with deprecated "analysis_level" as required input

### ISSUE THREAD

**Issue by AdinaWagner** [poldracklab/fitlins#102]
Ever since I started to use fitlins I've been confused why this required [`analysis_level`](https://github.com/poldracklab/fitlins/blob/c7cc798330a8fe8cea8ee545c64c7fb08d1a562b/fitlins/cli/run.py#L70) argument is (still) in existence: https://github.com/poldracklab/fitlins/blob/c7cc798330a8fe8cea8ee545c64c7fb08d1a562b/fitlins/cli/run.py#L70-L71

I believe it has been deprecated half a year ago, and I can't find it being used anywhere, but running fitlins without it leads to

```shell
usage: fitlins [-h] [-v]
               [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
               [-m MODEL] [-d DERIVATIVES [DERIVATIVES ...]]
               [--derivative-label DERIVATIVE_LABEL]
               [--space {MNI152NLin2009cAsym,,MNI152NLin6Sym}]
               [--include INCLUDE] [--exclude EXCLUDE] [--desc DESC]
               [--n-cpus N_CPUS] [--debug] [-w WORK_DIR]
               bids_dir output_dir {run,session,participant,dataset}
fitlins: error: the following arguments are required: analysis_level
```

I could try to contribute and make analysis_level a 'stopping criterion' to halt the computations once the specified analysis level is reached, if that is intended/useful functionality. Otherwise I could just remove it from argparse.

**Comment by effigies** [comment]
It's a requirement of the BIDS App spec. And yes, we should use it as a stopping criterion, probably in `LoadBIDSModel`.

**Comment by AdinaWagner** [comment]
ah, thanks for this clarification. I can try to make it a stopping criterion, lets see how far I get :-)
