### ISSUE TITLE
Color scale reversed from usual in brain plots

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#107]
Minor, but blue = positive, red=negative in fitlins brain plots. 

![ses-movie_task-movie_bold_contrast-facedetectionconfidence_ortho](https://user-images.githubusercontent.com/2774448/52440183-0fa62400-2ae3-11e9-9a4a-39394b7434a4.png)

**Comment by effigies** [comment]
Oh, weird. I could've sworn I did it the other way.

**Comment by adelavega** [comment]
You should have seen my face for a second.

**Comment by adelavega** [comment]
Roses are red, violets are blue, and in fitlins, your activation is too

**Comment by effigies** [comment]
Eh, "blue/too" is overdone. How about "Roses are red / debugging's a curse / we helpfully show / your blobs in reverse."
