### ISSUE TITLE
Enable AFNI estimators

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#115]
Related: #100

**Comment by effigies** [comment]
@yarikoptic @tyarkoni As the folks requesting non-nistats estimators, do either of you have any experience using 3dREMLfit and any other AFNI tools that might be needed to perform analysis?

**Comment by tyarkoni** [comment]
I don't... @shotgunosine, are you (or someone else in the group) able to help with this? It would be great to add AFNI support!

**Comment by yarikoptic** [comment]
Me neither, let's ping @agt24 as well or may be even @afni-rwcox himself?

**Comment by leej3** [comment]
Just wondering what this would entail? Would nipype interfaces be sufficient?

I talked with @afni-gangc briefly. Some of the programs that might be useful for voxelwise stats:

3dREMLfit would need 3dDeconvolve first (individual level)

And for group analysis:
3dMEMA is counterpart of FLAME
3dLME for LME
3dMVM for anova/ancova etc
3dttest++ for GLM

**Comment by effigies** [comment]
If we create the design matrix, do we need 3dDeconvolve?

But yes, nipype interfaces and possibly advice on best practices and pitfalls to be aware of.

**Comment by afni-rwcox** [comment]
If you create the design matrix, then you don’t need 3dDeconvolve. However, the format of design matrix we pass around contains extra information in its header that is useful, such as markers for which columns are “of interest” and which are part of the “baseline” (null hypothesis) model. Columns of interest get text labels to help mark them out in the final dataset. Censoring information can be included. And so on.

The standard option to 3dREMLfit (program for linear time series regression) is “-matrix FILENAME”, where FILENAME contains an XML element that encodes all this auxiliary data, as well as the matrix itself. The alternative is the “-matim FILENAME” option, which just takes an ASCII array of numbers. Here’s the help for that option:

-matim M  = Read a standard .1D file as the matrix.
            * That is, an ASCII files of numbers layed out in a
              rectangular array. The number of rows must equal the
              number of time points in the input dataset. The number
              of columns is the number of regressors.
            * Advanced features, such as censoring, can only be implemented
              by providing a true .xmat.1D file via the '-matrix' option.
            * An advanced intelligence could reverse engineer the XML
              format used by the .xmat.1D files, to fully activate all the
              regression features of this software :-)
           ** N.B.: You can use only 'Col' as a name in GLTs ('-gltsym')
                    with these nonstandard matrix input methods, since
                    the other column names come from the '-matrix' file.

**Comment by Shotgunosine** [comment]
I think this is resolved, the 3dREMLfit is working when you run fitlins with `--estimator afni`.
