### ISSUE TITLE
Delegating the optional smoothing to Nistats

### ISSUE THREAD

**Issue by kfinc** [poldracklab/fitlins#116]
Adding an option to delegate isotropic smoothing to Nistats by specifying FWHM in the model.json file.

**Comment by adelavega** [comment]
I wonder if it would ever make sense to delegate smoothing to preprocessing (since its quite a time consuming step)

**Comment by effigies** [comment]
The problem with doing it in preprocessing (i.e., before FitLins) is the disk space cost of maintaining the full time series. Here at least it only lasts as long as your nipype working directory. Improved caching, as being developed in Pydra, might help there, though.

**Comment by effigies** [comment]
Fixed in #118.
