### ISSUE TITLE
Rearchitect FitLins as a Nipype workflow

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#12]
Within a level, each fit/contrast step is independent, making this a good target for parallelization.

This thread is a place to make notes on ideas and steps taken before we get to the stage of opening a PR.

@satra @tyarkoni @adelavega We did a bit of strategizing on this in Austin, but it's taken a bit of a back burner until now. Feel free to add any points from those discussions you think important for directing this, or any ideas you may have had since.

**Comment by satra** [comment]
@effigies - sorry about the delay in responding.

is there a non-nipype example of a first level and group level analysis that i could look at. i'm assuming that means looking at a model spec, but also how smoothing, high-pass filtering, ar estimation, and other things are done. and how the end products of these are specified as input to fitlns.

**Comment by satra** [comment]
also, we should have surface and/or volume based analysis options in the workflow.

**Comment by effigies** [comment]
@satra Sorry about the delay. I was on vacation. 

From discussions with @chrisfilo our approach will be to specify the smoothing parameters in fitlins itself, rather than perform it on inputs. This is not currently implemented. High-pass filtering is partially handled using a discrete cosine filter bank, but this is currently hard-coded, which may not be the final approach. Similarly, I would think that AR estimation should be handled within FitLins. I will see if this is done automatically in nistats, or if we need to add a pre-whitening step.

Finally, surface and volume based analyses should be able to be handled through the use of the `--space` parameter, although surface-based analyses are not yet supported.

**Comment by effigies** [comment]
Closed by #30.
