### ISSUE TITLE
Location of output images when session is present & ignored

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#123]
When there is a `session` grouping, and it is not modeled, it seems that the group level images are output there.

For example, studyforrest has a session `ses-movie`, so all the group level images are under a folder `ses-movie`. When there is no session grouping, they would just be at the top level directory.

Shouldn't they be at the top level when the session is just ignored in the model? This makes it a bit inconsistent to know if they are group level images, and to locate them.

**Comment by adelavega** [comment]
As an example, here is a filename `ses-movie_task-movie_run-1_bold_contrast-framewiseDisplacement_stat.nii.gz`

From this, I gather session is higher in the hierarchy than `task` and that's why it gets its own folder?

**Comment by effigies** [comment]
Yeah, I think that's true. Are there any cases where we would want to preserve `session` outside the subject?

**Comment by tyarkoni** [comment]
One way to address this might be to dump a small JSON file in each output directory (if we're not already doing this) that contains metadata that makes it clear what the folder represents. E.g., `"Level": "dataset"`.

**Comment by adelavega** [comment]
I think the meta-data file helps.
I'm not so concerned about preserving `session`, as much as I think the `dataset` level stuff should be in the same place regardless. And actually, I think since `dataset` level supersedes `session`, it should probably not be preserved. If you wanted to do a session level analysis, that would be a contrast at the `dataset` level, correct?

**Comment by effigies** [comment]
That's a little difficult because sometimes you have multiple levels in the same directory, as there's no provision in BIDS for new subdirectories. Would it make sense to have `level-X` as a key/value pair in the filename? That might help with things like:

```
sub-01_task-nback_run-1_contrast-maineffect_zscore.nii.gz
sub-01_task-nback_run-2_contrast-maineffect_zscore.nii.gz
sub-01_task-nback_contrast-maineffect_zscore.nii.gz
```

It could be:

```
sub-01_task-nback_run-1_level-run_contrast-maineffect_zscore.nii.gz
sub-01_task-nback_run-2_level-run_contrast-maineffect_zscore.nii.gz
sub-01_task-nback_level-subject_contrast-maineffect_zscore.nii.gz
```

**Comment by tyarkoni** [comment]
That's pretty ugly, but has the benefit of being unambiguous, so I guess I'd go with it. Alternatively, we could drop that info in the sidecars (but I guess those won't contain anything else otherwise, so probably no reason to create them just for that).

**Comment by effigies** [comment]
Sidecars will still want `SourceFile` at minimum.

But the only place where we really run into this right now is the `run` level, because all other levels have corresponding directories. What if we add a `level-run` subdirectory that can sit inside the subject or session subdirectory?

```
sub-01/
    [ses-01]/
        level-run/
            sub-01_[ses-01_]task-nback_run-1_contrast-maineffect_zscore.nii.gz
        [sub-01_ses-01_task-nback_contrast-maineffect_zscore.nii.gz]
    sub-01_task-nback_contrast-maineffect_zscore.nii.gz
sub-02/
    ...
task-nback_contrast-maineffect_zscore.nii.gz
```

It's not spec compliant, but neither are our suffixes.

**Comment by tyarkoni** [comment]
If we have sidecars anyway, then I'd vote to put `Level` in there, and probably to make it mandatory for all images (whether or not the context is sufficient to determine level). That way we can be fully compliant and still eliminate any ambiguity. I'm not crazy about a `level-run` subfolder because I think it will throw some users for a loop the first time they see it.

**Comment by effigies** [comment]
Okay. The main reason I suggest it is that the output directories have the potential to get very full, and separating run-level from higher-level results might help significantly declutter. But we can always circle back to it later if that does turn out to be an issue.

**Comment by adelavega** [comment]
Either works for me... But I think I agree the level thing would be
confusing. Maybe we can separate by subject if clutter is such an issue

**Comment by tyarkoni** [comment]
Maybe we should call it `BIDSStatsModelLevel` or at least `AnalysisLevel` for clarity.

**Comment by adelavega** [comment]
Is the issue here that there is not a `run` level directory (even though we can have `subject`, `session`, etc dirs?)

I guess adding level as a key works for me, but it somehow feels kludgy.
