### ISSUE TITLE
First-level outputs

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#124]
In #48, we switched from z-scores to effect sizes in the first-level outputs. These are more useful at the second level, but not great for visualizing.

In https://github.com/nistats/nistats/pull/183, we added the ability to easily get all output types (['z_score'](https://github.com/effigies/nistats/blob/f57bea97e7f953088bd66f2c3cc10c60631b011a/nistats/contrasts.py#L224-L244), ['stat'](https://github.com/effigies/nistats/blob/f57bea97e7f953088bd66f2c3cc10c60631b011a/nistats/contrasts.py#L168-L195), ['p_value'](https://github.com/effigies/nistats/blob/f57bea97e7f953088bd66f2c3cc10c60631b011a/nistats/contrasts.py#L197-L222), 'effect_size', 'effect_variance'), so which of these are the most useful? Do people have opinions?

cc @satra @mgxd

**Comment by tyarkoni** [comment]
See #125 for semi-related thoughts about naming schemes.

Is there any reason we shouldn't output everything by default? Other than disk space, what's the downside? I think most users are probably going to want to have the flexibility to peruse a comprehensive set of results (I certainly would).
