### ISSUE TITLE
Test pybids 0.9 candidate

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#138]
Create branch pinning to https://github.com/bids-standard/pybids/pull/432 (currently at [`2bcdd85`](https://github.com/bids-standard/pybids/commit/2bcdd85c5d6370e9a3cfe79ddcba5fec7434704d)).

@adelavega If I create the branch can you install it on top of a recent Docker image, or do I need to set up CircleCI to push the branch to DockerHub?

**Comment by adelavega** [comment]
A branch works

**Comment by effigies** [comment]
Okay, I'll get that going shortly. I don't think I'll have time to test it today, but I don't want to block you.

**Comment by adelavega** [comment]
I'll probably test on NeuroScout's back end first.

**Comment by adelavega** [comment]
Maybe it's best to hold off until we merge #131 and #135?

**Comment by effigies** [comment]
Sure. I'm working on #131 right now.
