### ISSUE TITLE
Exceptions not propagating down to CLI, failing silently

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#17]
I'm guessing you know about this, but I still thought I'd make an issue so at least you can let me know how you are testing/debugging.

Exceptions seem to be captured in a way that they do not propagate down to the user. It's a bit confusing, because its not clear what went wrong. Running in IPython, I'm able to get to the tracebacks, so its not an urgent issue for me.

For example:

    docker run -v D:\datasets\:/datasets  -v E:\analyses\:/analysis fitlins  
    /datasets/data /analysis/out dataset --model /analysis/does_not_exist.json

The following fails because the mode file does not exist. However, running this command the full output I get is:

    /opt/conda/envs/neuro/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of            the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`. 
    from ._conv import register_converters as _register_converter
    Captured warning (<class 'UserWarning'>): No valid root directory found for domain 'derivatives'. Falling back on the Layout's root directory. If this isn't the intended behavior, make sure the config file for this domain includes a 'root' key.

When debugging in Ipython, I can see the relevant traceback:

    *** FileNotFoundError: [Errno 2] No such file or directory: '/analysis/does_not_exist.json'

**Comment by effigies** [comment]
That's not intentional. Do you have any more detailed traceback? If not, I can try to track this down, tomorrow.

**Comment by adelavega** [comment]
I think the issue stems from the `sys.exit` line in `create_workflow`. Since all Exceptions are captured, and the application simply calls `sys.exit(1)`, the traceback is suppressed. 

For my own testing, what I've done in simply delete that the try catch clause (temporarily), which allows me to see the full traceback in Ipython (when I run by importing `main`). 

On this topic, I'd suggest moving the `sys.exit` to `main`. This would make it easier to import `create_workflow` and work from there interactively, and separates the CLI logic from the analysis execution logic. I'm also still an advocate of making arguments to `create_workflow` explicit (and with sensible defaults), rather than attributes of the `opts` object, for the same reason. 

Either way, no rush, I have a workflow for getting the traceback so I'm happy for now. And I know you're in the process of making a big overhaul to `create_workflow`, so these are just suggestions to take into account.

**Comment by adelavega** [comment]
I think this has been addressed, correct? And should be made obsolete with the nipype 2nd level workflow anyways.

**Comment by adelavega** [comment]
This should no longer be an issue
