### ISSUE TITLE
Selectors is not defined

### ISSUE THREAD

**Issue by Shotgunosine** [poldracklab/fitlins#173]
Small error, but in the fitlins bids interface, if it can't find the bold file, the error message there is returning a selectors object, which doesn't exist. Probably just needs to be changed to something like:
```
                raise FileNotFoundError(
                    "Could not find BOLD file in {} with entities {}"
                    "".format(self.inputs.bids_dir, ents))
```

https://github.com/poldracklab/fitlins/blob/91ee3b875a3348bfcd7c73aaf6201f04be2dc78a/fitlins/interfaces/bids.py#L419-L421

**Comment by effigies** [comment]
Yeah, looks like it's supposed to be:

```Python
selectors = {**self.inputs.selectors, **ents}
bold_file = layout.get(**selectors)
```

Just above that.
