### ISSUE TITLE
Handle variables which only occur in some runs

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#176]
There are cases when you want to model an event that may only occur in certain runs, but not all.

However, nistats cannot handle events which have all missing values.

It would be useful to detect this situation, and only model the variable in the runs it occurs in.
Then, when doing the subject-level model, feed in only those runs that got modeled.

So in some instances, this may be all the runs, or as few as only a single run. 

This is sort of related to the globbing discussion (https://github.com/bids-standard/pybids/issues/487#issuecomment-532873218), but can also occur when you actually know the names you want to model. So without having to solve this problem at the spec-level, I think we can solve it for this subject of cases at the fitlins implementational level.

**Comment by effigies** [comment]
This seems reasonable. I think the sensible place to do this will be in the first level model, where we get the design matrix and can determine whether or not a variable is present. We output matched lists of contrasts and associated metadata, so we could just filter those, and I think everything else will fall into place.

**Comment by tyarkoni** [comment]
This should probably also be exposed as a command-line argument, possibly with the default set to fail in the event of missing data. I think the expected behavior at the first level is actually what @adelavega suggests above (i.e., silently dropping the runs with missing data), but beyond that I think it would be bad to, e.g., silently drop some subjects from a t-test without the user's knowledge. So defaulting to a conservative strategy, but giving a comprehensible error message like "please fix the problem or use --drop-missing", seems optimal to me.

**Comment by adelavega** [comment]
Another option is to limit this feature to the first level, as it has to do with nistats crashing with empty design matrix columns. A CLI flag seems good either way though.

**Comment by tyarkoni** [comment]
I think it makes sense to apply this at all levels; it's a fairly common scenario to have some contrasts missing for some subjects—e.g., in analyses involving correct vs. incorrect responses, it's common for some subjects to not have made any errors. The one scenario I think we want to avoid above all else is someone thinking they've done a group-level t-test on 40 people when it's actually based on 25 people, but there was no obvious failure. We could in principle have different defaults for different levels, but that would be even more confusing. So I'd just go with failure at all levels as the default. If we want to prevent users from getting half-way into estimation before it breaks, we could potentially introduce some pre-estimation validation (not sure if any is currently done, but there might be other things like this eventually).
