### ISSUE TITLE
Add command line option for saved bids layout

### ISSUE THREAD

**Issue by Shotgunosine** [poldracklab/fitlins#186]
I'm running on an HPC with a slow file system, and running one fitlins instance per run on the cluster. It'd be great if each of them didn't have to parse the entire input directory. Can we add a database_file parameter to the CLI to shorten that startup time?

**Comment by effigies** [comment]
Sure. Let's maybe call it an "expert option" and say that it's subject to change. Does `BIDSLayout` have a classmethod like `BIDSLayout.from_database()`?

**Comment by Shotgunosine** [comment]
No, I think it's just an option when the layout is instantiated.

**Comment by tyarkoni** [comment]
Would be trivial to add a `BIDSLayout.load()` classmethod if we want symmetry with `.save()`, but I figured it would just be API noise given that there's now a `database_file` argument to init that lets you indicate where you want the DB file to live (so loading just amounts to specifying a pre-existing file).

**Comment by effigies** [comment]
I didn't realize we had loading and saving at all. I don't care hugely about the API at this point, as long as it's coherent.
