### ISSUE TITLE
Save final design matrix to derivative

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#233]
I wonder if we should be outputting the final design matrix from nistats as an output in the derivative

Given that depending on the parameters, nistats adds columns to the design matrix, such as the drift model and a constant.

**Comment by effigies** [comment]
I'm pretty sure we construct the final design matrix ourselves, and that's what we save. Do you have an example where they don't match?

**Comment by adelavega** [comment]
Well as far as I can tell we're not saving design matrices to the `fitlins` output directory right? Just to the workdir, right?

**Comment by adelavega** [comment]
And yes, we do construct it ourselves, using nistats. I mean't we should save that as an output

**Comment by effigies** [comment]
Oh, if we don't, then I think there's another open issue, because I remember that being an issue at one point.

**Comment by adelavega** [comment]
nevermind, im blind
