### ISSUE TITLE
resting state  data

### ISSUE THREAD

**Issue by qasim85** [poldracklab/fitlins#240]
Hello
Is there a  way I can use fitlins for resting state data ? Ideally for the mask generated through the Freesurfer by fmriprep for each subject. If not, atleast the denoising/regression of the nuisance variable would be  still very helpful

Thanks

**Comment by effigies** [comment]
I don't think this would be a good fit for FitLins. Have you seen [fmridenoise](https://github.com/compneuro-ncu/fmridenoise)?
