### ISSUE TITLE
nilearn 0.7.0 contains nistats

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fitlins#261]
[nilearn 0.7.0 was released earlier today](https://github.com/nilearn/nilearn/releases/tag/0.7.0) which is the new home for nistats, in [`nilearn.glm`](https://github.com/nilearn/nilearn/tree/0.7.0/nilearn/glm). The next time dependencies are updated, nistats can be dropped.

**Comment by effigies** [comment]
Woo! Looking forward to it!
