### ISSUE TITLE
smoothing_fwhm not used in afni estimator

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fitlins#272]
https://github.com/poldracklab/fitlins/blob/6ec056a113306a26a79c0c169f1aef27c4ccb432/fitlins/interfaces/afni.py#L90-L92

It looks like the smoothing parameter is never applied to the data in the afni estimator. [nilearn](https://nilearn.github.io/modules/generated/nilearn.image.smooth_img.html) could be used to smooth the image before fitting if it's only important for the estimator to be from afni. (I couldn't find an obvious parameter in [REMLfit](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dREMLfit.html) that performs smoothing).

**Comment by adelavega** [comment]
Yes, we noticed the outputs from AFNI looked smoother than nilearn's so we were wondering if smoothing occured twice (once at run, once at dataset -- as requested).

**Comment by Shotgunosine** [comment]
Weird that they would be smoother, since AFNI isn't applying the smoothing
and nilearn is, unless I'm missing something when I look at the code.

**Comment by adelavega** [comment]
Well the smoothing for nilearn occurs at the Dataset level. 

It's possible AFNI is just so damn good (and we did use a very robust predictor -- volume-- with expected activation in auditory cortex), that the results just looked unexpectedly nice :)

Either way, it's a bug that the first level estimator accepts a smoothing kernel and does nothing with it.

**Comment by tyarkoni** [comment]
@adelavega have we directly compared the two on the same dataset? If not, maybe it's a preprocessing issue?

**Comment by adelavega** [comment]
Not yet, but soon!

**Comment by Shotgunosine** [comment]
Yeah, I was going to work on the afni fitlins estimator a bit at the beginning of the next week. I'll add handling smoothing to the todo list. Does anyone have any opinions about using nilearn as @jdkent suggested vs using something more AFNI specific like [3dBlurToFWHM](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dBlurToFWHM.html). If the goal is to be able to cleanly compare estimators I guess it makes sense to keep the smoothing the same.

**Comment by adelavega** [comment]
I'm fine using the AFNI one although we could in theory parameterize that as well.

**Comment by tyarkoni** [comment]
@adelavega I'm guessing the data the AFNI estimator is being applied to is being smoothed during preprocessing then, given that it's not going through fMRIPrep. That would be sub-optimal from a NeuroScout perspective independent of the present issue, so it might be something to look into...

**Comment by adelavega** [comment]
D'oh! You're right: Smoothing 6mm FWHM

**Comment by Shotgunosine** [comment]
I'd like to make BlurInMask and BlurToFWHM available for the afni estimator. Are there any objections to including `isoblurto` as a smoothing type?

**Comment by effigies** [comment]
No objections here.

**Comment by Shotgunosine** [comment]
I think this is now resolved by #280
