### ISSUE TITLE
TIME SENSITIVE: BIDS Stats Models OHBM abstract

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#281]
Hi all, and especially @Shotgunosine @jdkent @leej3 @kfinc and @adswa,

I'm submitting an abstract on the state of the BIDS Stats Models extension ([BEP002](https://bids.neuroimaging.io/bep002)) for OHBM. Since FitLins development has been an important part of working through the details of the spec, I want to invite all contributors as co-authors. If you would like to be an author, please add yourself to the author list at https://hackmd.io/@effigies/ohbm2021/edit, register on the [abstract submission site](https://ww4.aievolution.com/hbm2101/), and make any comments.

The deadline is midnight tonight, EST. Apologies for the late announcement; I only just thought to look for FitLins contributors who were not contributors elsewhere.

**Comment by adswa** [comment]
Thanks! I will take a look this evening.

**Comment by leej3** [comment]
Thanks Chris. Nice job!

**Comment by adelavega** [comment]
@effigies I'm going to go ahead and close this issue since it seems you've submitted your abstract.
