### ISSUE TITLE
Security discussion: Codecov event

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#283]
This morning (15 April 2021), I received a security update from CodeCov: https://about.codecov.io/security-update/

FitLins was affected because the CircleCI script uses the curl-bash approach to running CodeCov:

https://github.com/poldracklab/fitlins/blob/278208f013f2f900e3c68bab88831e227df198e9/.circleci/config.yml#L158-L161

This exposed my personal DockerHub and PyPI credentials that were stored on CircleCI. Passwords for both have been updated, and I've looked at the activity of these accounts from Jan 1-Apr 1 (the exposure window) and haven't seen evidence of any malicious behavior. I have also switched to API tokens on both services to further reduce the scope for compromise in the future.

I will leave this issue open for ~1 week for discussion.

**Comment by adelavega** [comment]
Wow, I actually dodged this bullet by messing my codecov script and it silently crashing for the last 6 months. First time that's paid off. 

Sounds good to me, disappointing though. I guess there's a reason they tell you not to execute random bash scripts.

**Comment by effigies** [comment]
Yeah. I would prefer to move to using the Python package. I feel like our test setup has built up significant technical debt, but not sure when I'll have the time to tackle it.
