### ISSUE TITLE
Abstract CLI-specific logic out

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#34]
To make it easier for me (or others) to use fitlins as a "library", it would be useful to abstract out logic specific to the CLI.

However, I know its not the intention for fitlins to be generally used a library, so I propose some minimalist changes. Currently the only issue I'm having relates to the `sys.exit` and retcode. Since `fitlins` forces a `sys.exit` this will also exit Neuroscout, and prevent me from doing any other operations following execution. An easy fix would be to add a `run` function that does what `main` does now (parse args, run `create_workflow`, etc), but simply returns the retcode. `main` would then call `run` and execute `sys.exit`. I would then import `run` instead of `main. 

Alternatively, parse args logic could be moved to `create_workflow` and `sys.exit` could be called in `main`, and I would import `create_workflow`.

**Comment by effigies** [comment]
Yeah, sorry, this has gotten messy. I generally support treating any Python program as a library, so let's go ahead and figure out an appropriate set of interfaces.

What are the inputs, outputs and actions of the function you need?

In order to behave correctly, we need a main function like:

```Python
def main():
    sys.exit(run_fitlins(sys.argv))
```

Here `run_fitlins` would be something like:

```Python
def run_fitlins(argv=None):
    opts = create_parser.parse_args(argv)
    retval = 0

    # Do everything, possibly updating retval
    ...

    return retval
```

I think under the current structure, `run_fitlins` is basically `create_workflow`, except that it will always return a numerical value instead of call `sys.exit`

Do we need a further abstraction away from `run_fitlins`? Something that will take the arguments read in by `parse_args` and turn them into parameters? Such as:

```Python
def fitlins_core(bids_dir, preproc_dir, fitlins_dir, model_file,
                 include_pattern, exclude_pattern, work_dir):
    # run first-level pipeline
    # run second-level loop
```

**Comment by adelavega** [comment]
Awesome. This is not high priority btw, as I have a hacked version that does essentially your first suggestion, and works well enough for the time being. Although, maybe a PR with just the first suggestion wouldn't be a bad idea, so I can run off master rather than my hacky fork.

Another issue I had with the previous setup is that catching Exceptions and returning a retval will often mask the true exception, making it hard to debug. But this is not an issue with `nipype` as it dumps all that information out. 

Ideally in the long run (once the second level is nipype'd), we could hash out all the arguments that `fitlins_core` would take. Ideally, all the defaults for each argument are specified here, rather than in `arg_parse`, which would be a more "proper" API.

**Comment by effigies** [comment]
> Another issue I had with the previous setup is that catching Exceptions and returning a retval will often mask the true exception, making it hard to debug. But this is not an issue with nipype as it dumps all that information out.

Yeah, we should just let exceptions error out, rather than return a bad return value. Python should take care of that for us.

**Comment by effigies** [comment]
Ah, I'm seeing why we caught the exceptions at such a high level. It was the fmriprep approach of trying to construct reports even for erroring data. Moving to nipype ought to help with this, but feel free to submit a PR to print out the traceback...
