### ISSUE TITLE
ReadTheDocs isn't building

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#384]
BOOOO

**Comment by adelavega** [comment]
Oddly, it is building. See this PR build: https://fitlins--378.org.readthedocs.build/en/378/

It has no mention of StatsModels.

For whatever reason, all the recent builds are PRs, which means that a build is not being triggered for "latest" (not even a failure, just not triggered)

**Comment by adelavega** [comment]
OH I bet you its because our default branch is `dev`, rather than `master`, which is where its expecting the code for `latest`

**Comment by adelavega** [comment]
Fixed

**Comment by adelavega** [comment]
Apparently I can't close issues

**Comment by effigies** [comment]
You could at one point... I re-added you as a collaborator.
