### ISSUE TITLE
Wrong preproc dir for second level

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#45]
https://github.com/poldracklab/fitlins/blob/958ffef320c8fca725e18743145697ded9eec13d/fitlins/cli/run.py#L153

Really minor, but `opts.preproc_dir` should be `preproc_dir`, since that variable is processed to have the correct directory, rather than just `fmriprep`

**Comment by effigies** [comment]
Good catch. Thought I'd taken care of that...
