### ISSUE TITLE
Output beta maps

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#46]
Currently, it seems fitlins only outputs stat maps. Outputting beta maps would be very useful.

**Comment by effigies** [comment]
Do you know how to get them from nistats?

**Comment by adelavega** [comment]
Nope

**Comment by effigies** [comment]
Being sure we're all speaking the same language is a constant worry for me, so forgive the over-explicitness.

I guess `'effect_size'` means `cope` and `'effect_variance'` means `varcope`? And if we have an identity contrast, `'effect_size'` will mean `pe` (which @adelavega is here calling a beta map)?

When I previously asked about this parameter, I was told they just use the `z_score` at every turn, so there's not much guidance about when you would want to use the various options. It takes some digging, but `'stat'` refers to either `t` or `F`.

**Comment by tyarkoni** [comment]
> Probably a little, but compared to finding the betas it should be negligible.

Agreed but it's also unnecessary and counterintuitive. There's a `Contrast` object that has slots for all these things and is generated anyway, so it would be easy enough to just return that. If they respond positively, maybe you can open a PR on nistats that adds an `output_type='Contrast'` option?

**Comment by effigies** [comment]
@adelavega Was this fixed in #48?

**Comment by adelavega** [comment]
yes
