### ISSUE TITLE
Missing values for confounds result in incorrect number of volumes

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#56]
Occasionally, confounds have missing values

For example, for `SherlockMerlin` sub-28 `MerlinMovie` task, the first volume for `FrameWiseDisplacement` is `n/a`. 

Regardless of the reason, we should be prepared to deal with such values.

Currently, the `n/a` value will be skipped (by pybids), and result in an incorrect number of volumes in the confounds file passed to nistats. Resulting in this error: 

```
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nistats/design_matrix.py", line 351, in make_design_matrix
    'time-frames: %d' % (add_regs.shape[0], np.size(frame_times)))
AssertionError: Incorrect specification of additional regressors: length of regressors provided: 1026, number of time-frames: 1027
```

The "proper" BIDS model solution would be the replace n/as with the mean value using  a transformation, but that seems too cumbersome. Probably best if fitlins does this if any n/as are detected in confounds.

**Comment by effigies** [comment]
Is there a consensus on what to do if you have confounds missing for some volumes?

**Comment by adelavega** [comment]
Doubt it, but replacing the with mean value seems like a reasonable solution (the "proper" BIDS model solution I discussed earlier).

Either way, I think the re-sampling function has a bug, because its returning the wrong number of volumes.

**Comment by tyarkoni** [comment]
You can set `skip_empty=False` in pybids to keep the column around even though it's all N/As. I'm not a fan of mean imputation in this context, and I don't think it would work in any case given that adding a constant value throughout a run would be collinear with the intercept (which is presumably already included).

I think the right thing to do in this case is (a) drop the run/subject, (b) leave the confound out for that run but include it for everyone else, or (c) not include the confound in the model for anyone. I think (a) is probably the best option in most cases.

**Comment by tyarkoni** [comment]
Oh, but if the issue is just with a *few* volumes within the scan, and the n/as are occurring for sparse data, then mean imputation is probably okay. There should probably be some fairly conservative cut-off though--e.g., more than 5% missing values, and the run gets trashed.

If pybids doesn't currently have any options for ignoring n/as, feel free to open an issue for that. I don't know that mean imputation should be part of pybids though; that does feel like a transformation thing to me, even if it's kind of a pain. Otherwise we lose on the reproducibility front.

**Comment by adelavega** [comment]
It's only a single missing value in this instance. And to be clear, the volume is not missing, just a value for a Sparse variable (for the first volume in this instance). I'll open a separate issue in pybids because I think I know what the problem is

Also, pybids in some ways already has mean imputation, if you use `scale` correctly.

**Comment by effigies** [comment]
Is it just that FramewiseDisplacement is defined on the diff of two volumes, and thus is undefined either at the first or last volume? Maybe zero-filling is appropriate, instead.

**Comment by adelavega** [comment]
Ah, that makes sense, and yes we should zero fill. I guess the larger question of which component should handle this, and in which way (silently? by default? for which variables?)

**Comment by effigies** [comment]
@chrisfilo Do you have an opinion here? My inclination is that this should be at the Nipype/fMRIPrep level.

**Comment by adelavega** [comment]
I think `n/a` is a fair value. Zero is technically incorrect. And this issue is more general and could crop up elsewhere.

**Comment by adelavega** [comment]
There *is* also a `fillna` argument that can be passed down from `get_design_matrix` which is an option for dealing with this. The problem right now is a bug which omits the value entirely rather than returning `n/a/.

**Comment by adelavega** [comment]
Now that that bug is fixed, I would vote for fitlins filling zeros in in confounds by default, but warning if it's doing so. Adding a transformation for this seems really clunky, although it would be more reproducible.

**Comment by chrisfilo** [comment]
Agreed, but I would do it only for FramewiseDisplacement and DVARS. Also mean of non-zero values is a better value to impute than zero.

**Comment by effigies** [comment]
Mean is better to impute for FD and DVARS? Or 0 for the first volume of FD and DVARS, and mean of non-zeros in general for `n/a`s found in other confounds?

**Comment by chrisfilo** [comment]
Mean is always always a better imputation value than an arbitrary constant (such as zero).

Imputing for all regressors comes with risks. I am worried about hiding issues with regressors. For FD and DVARS we are expecting this missing value to it makes sense to impute it. For other regressors I would not do imputation (at least until someone complains).

**Comment by effigies** [comment]
Looks like right now we're always imputing 0 for all confounds:

https://github.com/poldracklab/fitlins/blob/125bad90e087ab0b591f6983ac3e2fec5d25ef2e/fitlins/interfaces/bids.py#L204

So that needs fixing.
