### ISSUE TITLE
Separate CLI from from library

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#6]
Currently, the CLI and the fitlins library are very interlaced.
That is, it's currently not intuitive to use fitlins as a library that can be imported by another python program.

For example, default values for parameters come from argparse, and the function `create_workflow` takes a since opts argument, rather than explicitly stating the different inputs.

IMO, it would be useful to divorce these two a bit, so that `create_workflow` could be called without having to go through the CLI. This would make it easy for `neuroscout-cli` to wrap fitlinns without having to resort to using subprocess.

Thoughts?

**Comment by adelavega** [comment]
I suppose the counterargument here is that `run.py` *is* the CLI so if I want to use fitlins as a library, I should create an equivalent function that imports from `fitlins.base` etc, but it seems that `create_workflow` does a lot of important stuff and I think it'd be nice to use `fitlins` default wherever possible.

**Comment by effigies** [comment]
Sure, that's not too big a deal. The `create_workflow` is a hold-over from fmriprep, when I thought this would move quickly to a nipype workflow oriented approach.

The really fundamental bits are just the `init`, `first_level` and `second_level` in `fitlins.base`. It wouldn't be too hard to wrap those up with the 5 or 6 lines from `run.py`, but what would your ideal API look like?

**Comment by adelavega** [comment]
Hard to say right now, but probably something pretty simple like:

    analysis = Analysis(**opts)

`__init__` of `Analysis` would do a lot of what `create_workflow` does right now, including loading configs, prepping in/out dirs, creating the worklow

then:
    `analysis.run(n_procs=10)` 

which runs the workflow

One downside of moving the defaults out of argsparse I suppose is that its harder for a `CLI` user to see them.

**Comment by adelavega** [comment]
For now, let me poke around with reorganizing `create_workflow` a bit so I can call it from outside and we can worry more about a bigger refactor when my use case becomes more clear.

**Comment by effigies** [comment]
I think the easiest thing will be to wrap these lines in a function that provides all the necessary inputs (model, bids_dir, preproc_dir, deriv_dir, level):

https://github.com/effigies/fitlins/blob/e77409e062fd841d76615612a5b43cfff58eaf93/fitlins/cli/run.py#L210-L217

You can throw that into `fitlins.base` if you want.

I'm not a huge fan of the big fat config object approach to organizing, though, but I am thinking about this from a front-end perspective, not a library perspective. Be happy to consider any proposals you've got.

**Comment by adelavega** [comment]
That's fine, we could do that. It really doesn't matter much I'm mainly just trying to avoid using subprocess or requiring Docker while still fitlins and its defaults as if I were any other user from the command line. 

Those config objects *can* get pretty hairy and frankly I don't need to inspect them much  for now so using functions is fine w/ me.

**Comment by adelavega** [comment]
It might be a good time to revisit this issue. There are times when it would be useful to be able to pass in python objects to the fitlins API, which can't be done from the "command line" (or main call). 

For example, we would like to be able to pass in an initialized Layout, which indexes the appropriate neuroscout event files. 

For this to be the case, it would be nice for the defaults for arguments to be outside of argparse, and in a function call. 

Thoughts?

**Comment by effigies** [comment]
I guess what are all the arguments you actually want to pass? I think it might be better to factor out useful functional units, rather than turn the CLI-handling code into a functional entry-point.

**Comment by effigies** [comment]
And, similarly, what's the ideal output? A full-fledged BIDS derivative directory?

**Comment by tyarkoni** [comment]
The main sticking point for us right now is that the `BIDSLayout` initializer provides a lot of useful arguments, and trying to make fitlins a pass-through for all of them via the command line seems unwieldy. The biggest thing is to be able to run `create_workflow` with an arbitrary `BIDSLayout` or `Analysis` object. Other than that I don't know that we need anything to work differently.

**Comment by effigies** [comment]
Sorry, I'm not arguing for pushing everything through the command line, but it just seems that the function for converting CLI arguments into a runnable analysis might not be the best entry-point. What would make more sense to me is defining the inputs and outputs you're interested in, abstract that out, and have `neuroscout-cli` and `create_workflow` both call that.

A major reason for this hesitation is that I anticipate some pretty extreme volatility in `create_workflow` as I move to a nipype workflow. I guess if you're comfortable with that, we can go ahead and do this.

**Comment by tyarkoni** [comment]
To make this more concrete, the specific issue we're dealing with is that we're expecting to have this kind of structure in `derivatives`:

```
derivatives/
    fmriprep/
    neuroscout/
        analysis1/
        analysis2/
        ...
```
Where each invocation of fitlins should only scan the files in one of the analysis directories. This would be easy to do using the `BIDSLayout` initializer (e.g., via `include=['derivatives\/[fmriprep|analysis1]\/']`), but as far as I can see can't be done from the fitlins CLI right now. We can handle it by writing a custom `layout.json` file and dumping it in `derivatives/`, but then we would need to overwrite that file for each analysis run, which seems kludgy.
