### ISSUE TITLE
Handle models with >2 levels

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#64]
#30 dropped support for 3+ level models. To fix this, it will be easiest to find an example model to support.

**Comment by effigies** [comment]
@tyarkoni @chrisfilo @satra Do you know off-hand of any open datasets that would be amenable to a model with three non-trivial levels? (Nistats cannot handle the ds114 test-vs-retest model for ds114.)

**Comment by satra** [comment]
perhaps one of these:
 
- http://datasets.datalad.org/?dir=/openfmri/ds000117
- http://datasets.datalad.org/?dir=/openfmri/ds000102

they both have within session multi-run functional tasks

**Comment by tyarkoni** [comment]
@effigies what's the issue with ds114? Is it nistats that's the problem, or pybids? It will be a pretty big concern for us if we can't handle test/retest-type designs, so if this is a principled limitation of the way nistats is set up, we may want to start thinking about how we're going to handle this. (Also, I talked to Gael recently; nilearn is absorbing nistats in the near future, and they're open to reworking the API as part of that. So if we do need/want major changes, now is probably the time to raise them with the nilearn team.)

**Comment by effigies** [comment]
nistats/nistats#162

**Comment by satra** [comment]
@tyarkoni - every task in ds000114 has one run per task - hence it's kind of a trivial level 2. would be nice to use a dataset that has multiple runs per task.

completely agree that test/retest/longitudinal models should be supported.

**Comment by effigies** [comment]
Yes, that is the sense in which it's trivial; nistats cannot compute a second-level model of `[1 -1]`.

**Comment by tyarkoni** [comment]
Ah, got it. Cool, no worries then.

Independently of this, we should still think about what API changes we'd like to see in nistats. E.g., I'd like the sparse/dense format specification to be independent of whether one is passing in first or second-level variables, or convolved vs. non-convolved variables. If time allows, maybe we can talk about this briefly at the BIDS sprint this week.
