### ISSUE TITLE
Enable smoothing before any given level

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#75]
Smoothing may be a BIDS-model transform. Thoughts @tyarkoni? Or is that separate from the statistical considerations, and thus a runtime knob to turn?

**Comment by tyarkoni** [comment]
Good question... I'd prefer to exclude this from the scope of BIDS-Model. I don't think it could be represented as a transformation alongside all the other existing ones, for a variety of reasons (both spec-related and implementation-related), but we could potentially extend the spec to add a new class of transformations on image data. It's a big enough question it might be worth raising with other folks.

**Comment by adelavega** [comment]
Couldn't be in `config`?
