### ISSUE TITLE
File not found with n-cpu>1 on Windows reading from Datalad dataset

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#78]
To add to the pile of Windows specific errors, when running fitlins reading from a datalad directory (installed on a mounted volume, from within the container) with `n-cpu` > 1, the following error occurs on `prepoc` and `brainmask` files (seems random when it occurs):

```
traits.trait_errors.TraitError: The trait 'mask_file' of a FirstLevelModelInputSpec instance is an existing file name, but the path  '/data/Life/derivatives/fmriprep/fm
riprep/sub-rid000017/func/sub-rid000017_task-life_acq-374vol_run-01_bold_space-MNI152NLin2009cAsym_brainmask.nii.gz' does not exist.
ERROR:concurrent.futures:exception calling callback for <Future at 0x7fada756c5f8 state=finished raised BrokenProcessPool>
```

Not really sure what to do/say about it, except that it's a known issue, and its more the reason to get a Linux box for running analyses. On my Ubuntu laptop, this is not an issue. I'm guessing it's related to how Windows handles symlinks.

**Comment by adelavega** [comment]
Closing in favor of https://github.com/neuroscout/neuroscout-cli/issues/57 
I think I found a solution that I can implement into `neuroscout-cli`

**Comment by effigies** [comment]
This is my favorite kind of resolution.
