### ISSUE TITLE
wishlist/demand: tests and/or examples?

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/fitlins#82]
background: Together with @AdinaWagner we decided to dig ourselves into a rabbit hole and try to get fitlins work on a our sample (well, forrest gump) preprocessed (aligned according to BIDS Derivatives) dataset.  Some results have appeared as pull requests against PyBIDS which we took of the bleeding edge version.  We "dumbed down" our model.json from BEP002 to fitlins format (since support of BEP002 is just planned).  And now we are stuck at the point of https://github.com/poldracklab/fitlins/blob/master/fitlins/interfaces/bids.py#L276 .  pybids has changed output of `get_contrasts` and I thought to see how "original" fitlins+pybids worked on fitlins models, and thought to run the tests to get to that point, but as I discovered -- **there seems to be no single unittest or working example!** 
We have tried to run the beast on the sample ds000003 model, while forcing it to digest raw bids dataset:
```shell
$> fitlins ~/datalad/openfmri/ds000003/ output-ds0000003 run --participant-label 01 -m $PWD/fitlins-models/openfmri/ds000003/model.json -p ~/datalad/openfmri/ds000003/  
...
  File "/home/yoh/proj/bids/try-fitlins/venvs/dev/lib/python3.6/site-packages/bids/analysis/analysis.py", line 89, in setup
    b.setup(input_nodes, auto_contrasts, **selectors)
  File "/home/yoh/proj/bids/try-fitlins/venvs/dev/lib/python3.6/site-packages/bids/analysis/analysis.py", line 189, in setup
    collections = self.layout.get_collections(self.level, **kwargs)
  File "/home/yoh/proj/bids/try-fitlins/venvs/dev/lib/python3.6/site-packages/bids/layout/bids_layout.py", line 317, in get_collections
    skip_empty=skip_empty, **kwargs)
  File "/home/yoh/proj/bids/try-fitlins/venvs/dev/lib/python3.6/site-packages/bids/variables/io.py", line 73, in load_variables
    dataset = _load_time_variables(layout, dataset, **_kwargs)
  File "/home/yoh/proj/bids/try-fitlins/venvs/dev/lib/python3.6/site-packages/bids/variables/io.py", line 141, in _load_time_variables
    raise ValueError("No functional images that match criteria found.")
ValueError: No functional images that match criteria found.
```
which, from our "tour" through fitlins I think is due to looking for 
```shell
(git)hopa:~/proj/bids/try-fitlins/fitlins[master]git
$> git grep "'preproc" 
fitlins/interfaces/bids.py:            space = analysis.layout.get_spaces(type='preproc',
fitlins/interfaces/bids.py:            preproc_files = analysis.layout.get(type='preproc',
fitlins/workflows/base.py:                   selectors={'type': 'preproc', 'space': space}),
```

Is there an easy to try out example setup (model/dataset/command), even if it would be a toy one?

**Comment by effigies** [comment]
@yarikoptic Have you tried using [poldracklab/fitlins:0.1.0](https://hub.docker.com/r/poldracklab/fitlins/tags/)? That was working with the old draft model spec. Everything since then has been broken due to the churn in BIDS/pyBIDS.

What do your current dataset and model look like? And what versions are you using of pybids, grabbit and fitlins?

**Comment by effigies** [comment]
And datasets I've successfully run this on:

* ds000003 w/ https://github.com/poldracklab/fitlins/blob/models/openfmri/ds000003/model.json
* ds000030 w/ https://github.com/poldracklab/fitlins/blob/models/openfmri/ds000030/model.json

**Comment by yarikoptic** [comment]
Thank you @effigies , we will try to take tour into the past!  And are you saying it should work on "raw" BIDS ds000003 without any preprocessing whatsoever?  or should we fmriprep it first?

@AdinaWagner please adjust the nipype script to produce that "derivative" dataset (for now just leave the highpassed one as the `_desc-highpass_bold` to make life easier) and publish it on github and also on smaug, I will then publish its data from there to http://datasets.datalad.org

**Comment by effigies** [comment]
Ah, I used fMRIPrep. I believe I grabbed the preprocessed files off of OpenNeuro. (You can't run new analyses at this point, but you can still download old runs.)

**Comment by yarikoptic** [comment]
I do not see any `derivatives/fmriprep`  on https://openneuro.org/datasets/ds000003/ ...

**Comment by effigies** [comment]
Hmm. Let me look around. Possibly we'd run them on Sherlock.

**Comment by effigies** [comment]
Actually looks like a local run, from the command strings. Run on fMRIPrep 1.0.5 with options `--output-space template T1w --no-freesurfer`. If you have an open server where I can drop 4.2G of derivatives, let me know.

**Comment by AdinaWagner** [comment]
Yes, will try! Thanks!

**Comment by effigies** [comment]
Here's the pre-run fMRIPrep that @yarikoptic has kindly hosted: http://datasets.datalad.org/?dir=/labs/poldrack/ds003_fmriprep

**Comment by effigies** [comment]
Please check out the [docs](https://fitlins.rtfd.io) and create new issues if you need more docs/examples.
